plugins {
	id 'java'
	id 'application'
}

repositories {
	mavenCentral()
}

application {
	mainClass = 'ch.bbw.m450.tictactoe.TicTacToeMain'
}

dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.assertj:assertj-core:3.26.3'
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
}
